### ISSUE TITLE
update catalog yaml file

### ISSUE THREAD

**Issue by mayank0202** [sourcefuse/terraform-aws-arc-bootstrap#26]
example:-

```
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-aws-arc-ecs
  namespace: arc
  description: ARC Terraform module for provisioning an ECS Fargate cluster with alb
  annotations:
    snyk.io/org-id: 04111b7b-2ba8-404b-8a16-42a04448794d
    github.com/project-slug: sourcefuse/terraform-aws-arc-ecs
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://sourcefuse.github.io/arc-docs/arc-iac-docs/
      title: ARC Docs
      icon: dashboard
    - url: https://sourcefuse.github.io/arc-docs/arc-iac-docs/modules/terraform-aws-arc-ecs/
      title: ARC ECS Docs
      icon: dashboard
spec:
  type: service
  owner: sourcefuse
  lifecycle: development
```

update it accordingly so that snyk plugin should get enabled
